<?php

namespace Database\Seeders;

use App\Models\Template;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class AiTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $template = [
            [
                'template_name' => 'name',
                'prompt' => "please suggest subscription plan  name  for this  :  ##description##  for my business",
                'module' => 'plan',
                'field_json' => '{"field":[{"label":"What is your plan about?","placeholder":"e.g. Describe your plan details ","field_type":"textarea","field_name":"description"}]}',
                'is_tone' => '0',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'description',
                'prompt' => "please suggest subscription plan  description  for this  :  ##title##:  for my business",
                'module' => 'plan',
                'field_json' => '{"field":[{"label":"What is your plan title?","placeholder":"e.g. Pro Resller,Exclusive Access","field_type":"text_box","field_name":"title"}]}',
                'is_tone' => '1',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'name',
                'prompt' => "give 10 catchy only name of Offer or discount Coupon for : ##keywords##",
                'module' => 'coupon',
                'field_json' => '{"field":[{"label":"Seed words","placeholder":"e.g.coupon will provide you with a discount on your selected plan","field_type":"text_box","field_name":"keywords"}]}',
                'is_tone' => '0',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'meta_title',
                'prompt' => "Write SEO meta title for:\n\n ##description## \n\nWebsite name is:\n ##title## \n\nSeed words:\n ##keywords## \n\n",
                'module' => 'seo',
                'field_json' => '{"field":[{"label":"Website Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"Website Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"e.g.  cloud services, databases","field_type":"text_box","field_name":"keywords"}]}',
                'is_tone' => '0',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'meta_description',
                'prompt' => "Write SEO meta description for:\n\n ##description## \n\nWebsite name is:\n ##title## \n\nSeed words:\n ##keywords## \n\n",
                'module' => 'seo',
                'field_json' => '{"field":[{"label":"Website Name","placeholder":"e.g. Amazon, Google","field_type":"text_box","field_name":"title"},{"label":"Website Description","placeholder":"e.g. Describe what your website or business do","field_type":"textarea","field_name":"description"},{"label":"Keywords","placeholder":"e.g.  cloud services, databases","field_type":"text_box","field_name":"keywords"}]}',
                'is_tone' => '1',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'cookie_title',
                'prompt' => "please suggest me cookie title for this ##description## website which i can use in my website cookie",
                'module' => 'cookie',
                'field_json' => '{"field":[{"label":"Website name or info","placeholder":"e.g. example website ","field_type":"textarea","field_name":"title"}]}',
                'is_tone' => '0',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'cookie_description',
                'prompt' => "please suggest me  Cookie description for this cookie title ##title##  which i can use in my website cookie",
                'module' => 'cookie',
                'field_json' => '{"field":[{"label":"Cookie Title ","placeholder":"e.g. example website ","field_type":"text_box","field_name":"title"}]}',
                'is_tone' => '1',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'strictly_cookie_title',
                'prompt' => "please suggest me only Strictly Cookie Title for this ##description## website which i can use in my website cookie",
                'module' => 'cookie',
                'field_json' => '{"field":[{"label":"Website name or info","placeholder":"e.g. example website ","field_type":"textarea","field_name":"title"}]}',
                'is_tone' => '0',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'strictly_cookie_description',
                'prompt' => "please suggest me Strictly Cookie description for this Strictly cookie title ##title##  which i can use in my website cookie",
                'module' => 'cookie',
                'field_json' => '{"field":[{"label":"Strictly Cookie Title ","placeholder":"e.g. example website ","field_type":"text_box","field_name":"title"}]}',
                'is_tone' => '1',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name' => 'more_information_description',
                'prompt' => "I need assistance in crafting compelling content for my ##web_name## website's 'Contact Us' page of my website. The page should provide relevant information to users, encourage them to reach out for inquiries, support, and feedback, and reflect the unique value proposition of my business.",
                'module' => 'cookie',
                'field_json' => '{"field":[{"label":"Websit Name","placeholder":"e.g. example website ","field_type":"text_box","field_name":"web_name"}]}',
                'is_tone' => '1',
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'subject',
                'module'=>'ticket',
                'prompt'=> "generate example of  subject for bug in ecommerce base website support ticket",
                'field_json'=>'{"field":[{"label":"Ticket Description of Bug","placeholder":"e.g.Bug Summary","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'ticket',
                'prompt'=> "generate support ticket description of  subject for ##subject## ",
                'field_json'=>'{"field":[{"label":"Ticket Subject","placeholder":"e.g.Error Message Displayed","field_type":"textarea","field_name":"subject"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'reply_description',
                'module'=>'reply',
                'prompt'=> "generate a short  replay note for support ticket that topic is '##title##'. user must be note that '##description##'.",
                'field_json'=>'{"field":[{"label":"Ticket Title","placeholder":"Getting some issues while installation products.","field_type":"text_box","field_name":"title"},{"label":"Description","placeholder":"isuue is in his console account not in our product please follow google console api key creation step","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'note',
                'module'=>'note',
                'prompt'=> "generate a  note for support ticket that topic is '##title##'. in that note include this points '##description##'.",
                'field_json'=>'{"field":[{"label":"Ticket Title","placeholder":"Getting some issues while installation products.","field_type":"text_box","field_name":"title"},{"label":"Description","placeholder":"isuue is in his console account not in our product please follow google console api key creation step","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'title',
                'module'=>'knowledge',
                'prompt'=> "list out  title of Knowledge base in support ticket system for customer the  title relate to the category of '##categoty##'",
                'field_json'=>'{"field":[{"label":"Knowledge Category Title","placeholder":"Installation","field_type":"text_box","field_name":"categoty"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'knowledge',
                'prompt'=> "generate catchy detail user friendly description for this knowledge base  title : '##title##' please note that description should be usable for support ticket system",
                'field_json'=>'{"field":[{"label":"Title","placeholder":" How to Install Our Software","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'title',
                'module'=>'knowledge_category',
                'prompt'=> "list out category title of Knowledge in support ticket system for customer  the category title relate to the topic of '##title##'",
                'field_json'=>'{"field":[{"label":"Topic","placeholder":"Product Information","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'title',
                'module'=>'faq',
                'prompt'=> "IT company's web service support ticket system,please  suggested  some  number  of only topic name of Question  that asked by users repeatedlly in web service support relate to ##relate##.",
                'field_json'=>'{"field":[{"label":"FAQ Description","placeholder":"Installation","field_type":"text_box","field_name":"relate"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'faq',
                'prompt'=> "generate catchy detail user friendly description for this question topic : '##title##' please note that description should be usable for support ticket system",
                'field_json'=>'{"field":[{"label":"FAQ Title","placeholder":"Product Information","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'name',
                'module'=>'lead',
                'prompt'=>"generate lead  name form this description : ##description##",
                'field_json'=>'{"field":[{"label":"Lead description","placeholder":"e.g. example website ","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'subject',
                'module'=>'lead',
                'prompt'=> "Generate a lead subject line for a marketing campaign targeting potential customers for a software development company specializing in web and mobile applications.",
                'field_json'=>'{"field":[{"label":"Description","placeholder":"e.g.","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'notes',
                'module'=>'lead',
                'prompt'=> "Generate short description Note for lead ##description##",
                'field_json'=>'{"field":[{"label":"Lead description","placeholder":"e.g. create notes for lead user ","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'subject',
                'module'=>'lead_call',
                'prompt'=> "generate call for title that justify this resoan ##description## for the call.  please note that this call is for lead",
                'field_json'=>'{"field":[{"label":"Call Resoan","placeholder":"e.g.Time Management Strategy Call","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'lead_call',
                'prompt'=> "Generate a short note summarizing the key points discussed during a lead '##name##' call. The purpose of the note is to capture important details and action items discussed with the ##name## lead. Please structure the note in a concise and organized manner.",
                'field_json'=>'{"field":[{"label":"Lead name","placeholder":"e.g.  ","field_type":"textarea","field_name":"name"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'notes',
                'module'=>'lead_notes',
                'prompt'=> "Generate short description Note for lead ##description##",
                'field_json'=>'{"field":[{"label":"Lead description","placeholder":"e.g. create notes for lead user ","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'subject',
                'module'=>'lead_email',
                'prompt'=> "Write 10 catchy email subject lines for this email Description: ##description##  ",
                'field_json'=>'{"field":[{"label":"Email Description","placeholder":"","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'lead_email',
                'prompt'=> "Generate a short note summarizing the key points discussed during a lead '##name##' email. The purpose of the note is to capture important details and action items discussed with the ##name## lead. Please structure the note in a concise and organized manner.",
                'field_json'=>'{"field":[{"label":"Lead name","placeholder":"e.g.  ","field_type":"textarea","field_name":"name"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'name',
                'module'=>'deal',
                'prompt'=>"generate deal name for this proposal description ##description##" ,
                'field_json'=>'{"field":[{"label":"Proposal Description","placeholder":"e.g.","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'notes',
                'module'=>'deal',
                'prompt'=> "Generate short description Note for lead ##description##",
                'field_json'=>'{"field":[{"label":"Deal description","placeholder":"e.g. example website ","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'subject',
                'module'=>'deal_call',
                'prompt'=> "generate call for tile that justify this resoan ##description## for the call ",
                'field_json'=>'{"field":[{"label":"Call Resoan","placeholder":"e.g.Time Management Strategy Call","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'deal_call',
                'prompt'=> "Generate a short note summarizing the key points discussed during a lead '##name##' call. The purpose of the note is to capture important details and action items discussed with the ##name## lead. Please structure the note in a concise and organized manner.",
                'field_json'=>'{"field":[{"label":"Lead name","placeholder":"e.g.  ","field_type":"textarea","field_name":"name"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'notes',
                'module'=>'deal_notes',
                'prompt'=> "Generate short description Note for lead ##description##",
                'field_json'=>'{"field":[{"label":"Lead description","placeholder":"e.g. create notes for lead user ","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],

            [
                'template_name'=>'subject',
                'module'=>'deal_email',
                'prompt'=> "Write 10 catchy email subject lines for this email Description: ##description##  ",
                'field_json'=>'{"field":[{"label":"Email Description","placeholder":"","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'deal_email',
                'prompt'=> "Generate a short note summarizing the key points discussed during a lead '##name##' email. The purpose of the note is to capture important details and action items discussed with the ##name## lead. Please structure the note in a concise and organized manner.",
                'field_json'=>'{"field":[{"label":"Lead name","placeholder":"e.g.  ","field_type":"textarea","field_name":"name"}]}',
                'is_tone'=> 1,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'name',
                'module'=>'deal task',
                'prompt'=>"Generate a task name for this decription that specifically related to ##instruction##.",
                'field_json'=>'{"field":[{"label":"Task Instruction","placeholder":"e.g.","field_type":"textarea","field_name":"instruction"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'title',
                'module'=>'cases',
                'prompt'=>"Create a case title for a legal scenario involving \n\n ##description## \n\n. Ensure the title reflects the essence of the case and highlights its significance '##keywords##'.",
                'field_json'=>'{"field":[{"label":"Case highlights","placeholder":"your case highlights in keywords","field_type":"text_box","field_name":"keywords"},{"label":"Description","placeholder":"your case brief","field_type":"textarea","field_name":"decsription"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'case_description',
                'module'=>'cases',
                'prompt'=>"Generate a concise description for a legal case based on the given title and highlights. \n\n 'Title:' ##title## \n\n  'Highlights:' ##description##.",
                'field_json'=>'{"field":[{"label":"Case Title","placeholder":"your case title","field_type":"text_box","field_name":"title"},{"label":"Brief Case highlights","placeholder":"your case highlights in brief keywords","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'type',
                'module'=>'document_type',
                'prompt'=>"Generate a unique and professional Document Type name for a '##description##'. Ensure that the name is concise, clear, and relevant to the content it represents.",
                'field_json'=>'{"field":[{"label":"Document description","placeholder":"case evidance","field_type":"textarea","field_name":"description"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'document_description',
                'module'=>'document_type',
                'prompt'=>"Create a detailed and informative description for a '##title##'. The description should highlight the purpose, key features, and intended audience of the document. Aim for clarity and conciseness. Provide relevant information that would guide someone in understanding the document type and its significance.",
                'field_json'=>'{"field":[{"label":"Document Type","placeholder":"Case Integrity Verification Repor","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'sub_type',
                'module'=>'document_sub_type',
                'prompt'=>"Generate a suitable Document Subtype name for the given Main Type: '##title##'.",
                'field_json'=>'{"field":[{"label":"Document type","placeholder":"Evidence Authentication Brief","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'document_sub_description',
                'module'=>'document_sub_type',
                'prompt'=>"Create a detailed and informative description for a '##title##'. The description should highlight the purpose, key features, and intended audience of the document. Aim for clarity and conciseness. Provide relevant information that would guide someone in understanding the document type and its significance.",
                'field_json'=>'{"field":[{"label":"Document Sub Type","placeholder":"Case Integrity Verification Repor","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],
            [
                'template_name'=>'description',
                'module'=>'bill',
                'prompt'=>"generate bill description for this ##title##.",
                'field_json'=>'{"field":[{"label":"Bill is for?","placeholder":"case paper work fees","field_type":"text_box","field_name":"title"}]}',
                'is_tone'=> 0,
                "created_at" => date('Y-m-d H:i:s'),
                "updated_at" => date('Y-m-d H:i:s'),
            ],

        ];
        Template::insert($template);
    }
}
